Feature: Add option to return API response or dowload labels on checkout
askhelmut/posthorn pull request #1
Opened 2019-03-28 13:16 UTC by dahoo

2019-03-28 15:42 UTC, nhoffmann requested changes
No test?

2019-03-28 18:09 UTC, nhoffmann approved these changes
Some minor style issues, LGTMO

2019-03-28 18:09 UTC, nhoffmann commented on spec/office_spec.rb
> +  describe "checkout!" do
It seems like the project uses single quotes.

2019-03-28 18:09 UTC, nhoffmann commented on spec/office_spec.rb
> +      let(:labels) { office.checkout!(page_format: 25, download_labels: false) }
It feels weird to name the response `labels`, when it is an api response.

2019-03-29 12:31 UTC, merged

2019-03-29 12:33 UTC, dahoo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Als Admin möchte ich die API der Post nutzen, um direkt Briefmarken zu erzeugen](https://trello.com/c/EmeyEuqI/2034-als-admin-m%C3%B6chte-ich-die-api-der-post-nutzen-um-direkt-briefmarken-zu-erzeugen)